steps:
# Step 1: Generate access token and write Docker config for GCR
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    TOKEN=$(gcloud auth print-access-token)
    echo "{\"auths\":{\"gcr.io\":{\"auth\":\"$(echo -n "oauth2accesstoken:$$TOKEN" | base64)\"}}}" > /docker-config/config.json
  volumes:
  - name: 'docker-config'
    path: '/docker-config'

# Step 2: Run Gradle build with Jib using the token-based Docker config
- name: 'gradle:8-jdk21'
  entrypoint: 'gradle'
  args: ['clean', 'jib']
  env:
  - 'DOCKER_CONFIG=/docker-config'
  volumes:
  - name: 'docker-config'
    path: '/docker-config'

# Step 3: Apply Kubernetes manifests to GKE cluster
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=allprojects-cluster'
