steps:
# Step 1: Configure Docker to use gcloud as a credential helper
# This step uses the gcloud builder to run 'gcloud auth configure-docker'.
# The Docker configuration is written to a shared volume.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud auth configure-docker
  volumes:
  - name: 'docker-config'
    path: '/root/.docker' # Standard location for Docker config

# Step 2: Run your Gradle build with Jib
# This step uses the gradle builder and mounts the same shared volume.
# Jib will then find the configured Docker credentials in the mounted volume.
- name: 'gradle:8-jdk21' # Or your preferred Gradle/JDK version
  entrypoint: 'gradle'
  args: ['clean', 'jibBuild']
  volumes:
  - name: 'docker-config'
    path: '/root/.docker' # Mount the same volume here
  # If your project requires a specific JAVA_HOME, you might need to set it here
  # env: ['JAVA_HOME=/usr/lib/jvm/java-17-openjdk'] # Example, check your gradle image for correct path

# Step 3: Apply Kubernetes manifests from a folder to your GKE cluster
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=allprojects-cluster'
