server:
  port: 8080
  tomcat:
    threads:
      max: 5
# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'
#   endpoint:
#     health:
#       show-details: always      
    