server:
  port: 8080
  tomcat:
    threads:
      max: 2
# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'
#   endpoint:
#     health:
#       show-details: always      
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/CoderPraBhuApi
management:
  health:
    probes:
      enabled: true